[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "heterogeneous-multi-agent-systems"
authors = [{name = "Amaury SAINT-JORE", email = "amausj@gmail.com"}]
dynamic = ["version", "description"]

[project.optional-dependencies]
doc = ["sphinx",]